# Generated by Django 5.2.7 on 2025-10-14 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField(help_text='Hours used in current cycle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_distance', models.FloatField(blank=True, null=True)),
                ('estimated_duration', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('duration_hours', models.FloatField(default=10)),
                ('sequence', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_stops', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driving_hours', models.FloatField()),
                ('on_duty_hours', models.FloatField()),
                ('off_duty_hours', models.FloatField()),
                ('total_cycle_hours', models.FloatField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('duration', models.FloatField()),
                ('instructions', models.TextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
